---
- hosts:  all
  become:  true
  - name: Ensure the group Cow exists using sAMAccountName
    win_domain_group:
      name: Cow
      scope: global
      path: OU=groups,DC=ansible,DC=local

  - name: Ensure the group Cow doesn't exist using the Distinguished Name
    win_domain_group:
      name: CN=Cow,OU=groups,DC=ansible,DC=local
      state: absent

  - name: Delete group ignoring the protection flag
    win_domain_group:
      name: Cow
      state: absent
      ignore_protection: yes

  - name: Create group with delete protection enabled and custom attributes
    win_domain_group:
      name: Ansible Users
      scope: domainlocal
      category: security
      attributes:
      mail: helpdesk@ansible.com
      wWWHomePage: www.ansible.com
      ignore_protection: yes

  - name: Change the OU of a group using the SID and ignore the protection flag
    win_domain_group:
      name: S-1-5-21-2171456218-3732823212-122182344-1189
      scope: global
      organizational_unit: OU=groups,DC=ansible,DC=local
      ignore_protection: yes

  - name: Add managed_by user
    win_domain_group:
      name: Group Name Here
      managed_by: Domain Admins

  - name: Add group and specify the AD domain services to use for the create
    win_domain_group:
      name: Test Group
      domain_username: user@CORP.ANSIBLE.COM
      domain_password: Password01!
      domain_server: corp-DC12.corp.ansible.com
      scope: domainlocal
